#! /bin/bash

focus=""
output="mlcfg/cdsat.mlcfg"
if [ -z ${1+x} ]
then
  focus=""
else
  focus="--focus-on=$1"
  output="mlcfg/$1.mlcfg"
fi

cargo clean -p cdsat &&


cargo creusot $focus --span-mode=absolute --output-file=$output &&
 ./ide $output

