#! /bin/bash

focus=""
output="mlcfg/cdsat.coma"
if [ -z ${1+x} ]
then
  focus=""
else
  focus="--focus-on=$1"
  output="mlcfg/$1.coma"
fi

cargo clean -p cdsat &&


cargo creusot $focus --span-mode=absolute --output-file=$output  &&
 ./ide $output

