#! /bin/bash

focus=""

if [ -z ${1+x} ]; then focus="" ; else focus="--focus-on=$1" ; fi

cargo clean -p cdsat &&

cargo creusot $focus --span-mode=absolute -- --features=contracts &&

 ../creusot/ide target/debug/cdsat-bin.mlcfg

